spring:
  application:
    name: security-demo

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9595



#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG